# Generated by Django 4.1.1 on 2022-09-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('field_type', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('React', 'React'), ('Angular', 'Angular'), ('Node', 'Node'), ('PHP', 'PHP')], max_length=50)),
                ('User_type', models.CharField(choices=[('TL', 'TL'), ('Tranni', 'Tranni')], max_length=50)),
                ('assigned_client', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Traning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('InProcess', 'InProcess'), ('Complete', 'Complete')], max_length=50)),
                ('Start_traning_date', models.DateField()),
                ('End_traning_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_traning_date', models.DateField()),
                ('End_traning_date', models.DateField()),
                ('Topic_of_assignment', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
